GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator

- src/vk_mem_alloc.h
The word "subset" is used when it should be "superset" instead.
> Correct wording of comment about required flags

- src/vk_mem_alloc.h
vmaAllocateMemory, vmaAllocateMemoryForBuffer, and vmaAllocateMemoryForImage all return before filling out the VmaAllocationInfo struct.
> Fill out the VmaAllocationInfo parameter passed to vmaAllocateX.

- src/vk_mem_alloc.h
Fixes compile errors with `VmaVector` and ensures that `memcpy` is always declared
> Fix memcpy and VmaVector compile errors

- src/vk_mem_alloc.h
Currently, VmaStat is not defined as typedef.
With GCC, this is not compiling.
Just a small fix!
> Robustify VmaStat

- src/vk_mem_alloc.h
This patch forces the header to be compiled as C.
This behavior allows to use this library in a C program.
> Fix name mangling for C

- src/vk_mem_alloc.h
One was an out-of-order member in the constructor, which seems uncontroversial.
The other is an unused variable (heapIndex); is it meant to be used, or should that line be deleted entirely?
> Fixed some avoidable warnings when building with -Wall

- src/vk_mem_alloc.h
Hi,
I got a compile error on macOS.
```
vk_mem_alloc.h:
1855:12: error:
use of undeclared identifier 'VMA_NULL'
return VMA_NULL;
```
And, I fixed the issue.
Thank you.
OS: Mac OS X 10.13.3
Compiler: clang-900.0.39.2
> Fix undeclared identifier for Apple.

- src/vk_mem_alloc.h
`aligned_alloc` is defined in `<stdlib.h>`even on Linux. [FreeBSD](https://github.com/freebsd/freebsd/commit/2ffad81b1757554bf9413d11af0e92c93a94575b), [DragonFly](https://github.com/DragonFlyBSD/DragonFlyBSD/commit/02b66c54cac986a0bf93435b8d5ae1b17521515b), [OpenBSD](https://github.com/openbsd/src/commit/d88f57029e5acaaaf028633c7fa15c5d7325c5cc) don't support `<malloc.h>` while GNU libc uses `<malloc.h>` for non-standard extensions: `malloc_usable_size`, `mallinfo`, `memalign`, `pvalloc`, etc.
> Unbreak on BSDs

- src/vk_mem_alloc.h
I tend to define this one globally. To avoid redefinition warnings, it's best to check if it's already been defined.
> Avoid redefinition warnings of NOMINMAX by checking if it's already been defined.

- src/vk_mem_alloc.h
If `allocationCount` is zero, `res` would be uninitialized here.
> Fix for "potentially uninitialized variable" warning

- src/vk_mem_alloc.h
- Correctly handle VMA_STATS_STRING_ENABLED define and undefine method not being used.
- Remove unused freeSpaceBlockSize variable.
> Fixes VMA_STATS_STRING_ENABLED define and unused variable warning

- src/vk_mem_alloc.h
Fixed an issue where defining the VMA_USE_STL_CONTAINERS
macro would prevent VMA from compiling. This was caused by calling a
VMA-container-specific function instead of the macro meant for
abstracting away the differences.
This fixes #60
> Fixed an issue with STL_CONTAINER compilation.

- src/vk_mem_alloc.h
I couldn't build for Android armv7a without this change.
> Use VK_NULL_HANDLE for VkBuffer init (not VMA_NULL)

- src/vk_mem_alloc.h
Fixes #68, if `VMA_DEBUG_MARGIN` is <= ` 0` (the default)
This has the additional effect of preventing `-Wcast-align` warnings (again, as long as `VMA_DEBUG_MARGIN` is <= `0`):
```
vk_mem_alloc.h:3729:22: error: cast from 'char *' to 'uint32_t *' (aka 'unsigned int *') increases required alignment from 1 to 4 [-Werror,-Wcast-align]
uint32_t* pDst = (uint32_t*)((char*)pData + offset);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vk_mem_alloc.h:3743:28: error: cast from 'const char *' to 'const uint32_t *' (aka 'const unsigned int *') increases required alignment from 1 to 4 [-Werror,-Wcast-align]
const uint32_t* pSrc = (const uint32_t*)((const char*)pData + offset);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Guard VmaWriteMagicValue / VmaValidateMagicValue on VMA_DEBUG_MARGIN > 0

- src/vk_mem_alloc.h
The std::vector constructor used (count + allocator) is only available in C++14 (see: https://en.cppreference.com/w/cpp/container/vector/vector) and compiling with C++11 and `VMA_USE_STL_VECTOR` will result in compile errors. This adds a new constructor and switches to using that for compatibility.
> Adding a VmaVector constructor for C++11 compatibility

- src/VmaUsage.h
- src/vk_mem_alloc.h
Hi there! I'm developing a Vulkan graphics backend for a C# game framework, and I would very much like to use VMA for memory management. However, I quickly found out that there is no way to directly use VMA with C# on Windows. For obvious reasons I can't include the header file in my project, and even if the library is compiled as a DLL, the functions aren't exported. So I wrote up a fix!
This PR adds a new define (`VMA_STANDALONE`) that will export all the API functions (via `__declspec(dllexport)`) with the C calling convention (`__cdecl`), wrapped into easily modifiable macros. With these changes, it's simple to build the library into a standalone DLL for consumption on Windows.
Not sure if this benefits other platforms or not, but it works great for Windows. Thanks to the code in this …
> Export functions for building as a Windows standalone library

- src/vk_mem_alloc.h
Function aligned_alloc was [added to C++17](https://en.cppreference.com/w/cpp/memory/c/aligned_alloc); using it in older build environment causes compilation error (e.g. in GCC 5.4.0 or Clang 3.4.2).
This change in ifdef fixes this problem for older build environments.
Build log *without* this change:
````
+ g++ --version
g++ (SteamRT 5.4.0-7.really.6+steamrt1.2+srt2) 5.4.1 20160803
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+ g++ -std=c++14 test.cpp -lvulkan
In file included from test.cpp:2:0:
source/src/vk_mem_alloc.h: In function 'void* VmaMalloc(const VkAllocationCallbacks*, size_t, size_t)':
source/src/vk_mem_alloc.h:3354:96: …
```
> Use fallback aligned_alloc for pre-C++17 glibc++

- README.md
Could be interesting for C++ programmers already using Vulkan-Hpp.
> Mention VulkanMemoryAllocator-Hpp in README

- src/VmaUsage.h
With this change the llvm\clang-cl.exe can compile the Vma with warning level 4.
> Added clang compile support on windows

- src/vk_mem_alloc.h
In C++17 the method is called: https://en.cppreference.com/w/cpp/thread/shared_mutex/try_lock_shared
> Fix C++17 shared_mutex compile error

- src/vk_mem_alloc.h
Basically what the title says. The loops completely fails, which prevents VMA from being able to use multiple defragmentation passes to just move a subset of the data (eg. throw 10k objects at the defragmenter, and then do 10 passes with a `moveCount` of just 1000)
> Fixed incorrect for loop in ProcessDefragmetnations()

- src/vk_mem_alloc.h
I made this small change to the device-memory callback functionality. At present you would have to rely on global state to do anything meaningful with the callback. Adding this optional field allows the user to interpret the pointer however they wish during the callback and use custom data.
More concrete example:
I wanted to use `VK_EXT_debug_utils` object-names to name all device-allocations made by VMA as "VMA DeviceMemory #X". All my data was not stored globally but in a struct, so to do this with the current callbacks I had to create global pointers that pointed into my struct. Adding this simple field allowed me to interpret the `pUserData` as a pointer into one of my structs, no longer having to rely on global state.
This to consider when merging this PR:
Not much since this …
> Add pUserData to VmaDeviceMemoryCallbacks

- src/Doxyfile
- src/vk_mem_alloc.h
These are only present on the declarations in the C API.
New macros
- `VMA_NULLABLE`
- `VMA_NOT_NULL`
- `VMA_NULLABLE_NON_DISPATCHABLE`
- `VMA_NOT_NULL_NON_DISPATCHABLE`
- `VMA_LEN_IF_NOT_NULL`
On clang `VMA_NOT_NULL` and `VMA_NULLABLE` are defined as `_Nonnull` and
`_Nullable`. Clang will use these annotations to generate diagnostics
when these functions or structs are incorrectly used.
`VMA_NULLABLE_NON_DISPATCHABLE` and `VMA_NOT_NULL_NON_DISPATCHABLE` are
not defined on platforms where Vulkan's non-dispatchable handles are not
pointers; on platforms where they are, these macros are defined to be
`VMA_NULLABLE` and `VMA_NOT_NULL` respectively.
`LEN_IF_NOT_NULL` is not defined for any compiler. It is included to
mirror the `len` attribute in the Vulkan XML spec in order to aid in …
> Add annotations for nullability and length

- src/vk_mem_alloc.h
The quick start guide provides a minimal example of instantiating a `VmaAllocator`. Unfortunately the example is incorrect, as the `instance` field (type `VkInstance`) in the `VmaAllocatorCreateInfo` struct is not optional anymore. 
Without providing a value for this field the user hits the assert on line 15503:
`VmaAllocator_T::VmaAllocator_T(const VmaAllocatorCreateInfo*): Assertion pCreateInfo->physicalDevice && pCreateInfo->device && pCreateInfo->instance' failed.`
This small PR updates the quick start docs to reflect this.
> Update quick start docs to reflect that instance is not optional

- src/vk_mem_alloc.h
We want to know if the memory is mappable, which means that the memory properties should include the `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`.
> Correct if in mapping example

- src/vk_mem_alloc.h
Also fixes a typo in the comment.
> Fix VMA_DYNAMIC_VULKAN_FUNCTIONS compilation errors when VK_NO_PROTOTYPES is defined

- src/vk_mem_alloc.h
Our internal linter caught these.
> Fix misspellings.

- src/vk_mem_alloc.h
These fix a bit of "namespace pollution" caused by vk_mem_alloc.h. Nothing really dramatic, but I noticed them by chance...
NOMINMAX - this would have been defined in any source file including vk_mem_alloc.h. Granted, a lot of people probably define NOMINMAX anyway, and there aren't that many sane reasons to not do that... but strictly speaking, having this define will change how some (unrelated) user code may be interpreted, and thus that little bit of control should be left to them as well. Since VMA only needs that option in the "implementation" part, limit the definition's scope to that.
Similarly, defining VMA_RECORDING_ENABLED pulls in a number of headers which are only really needed in the implementation part, so move the includes there.
> Move some preprocessor directives that may influence user code into "implementation" block

- src/vk_mem_alloc.h
* Make vma_aligned_alloc() static (as other internal functions)
* For symmetry, add vma_aligned_free(), and rename VMA_SYSTEM_FREE to VMA_SYSTEM_ALIGNED_FREE.
> Some tweaks to vma_aligned_alloc()

- src/vk_mem_alloc.h
Our internal static analysis flags potentially unsafe midpoint
calculations. The proposed fix ensures the binary search doesn't
overflow at the cost of a single additional operation.
> Make binary search overflow safe

- src/vk_mem_alloc.h
The only change this commit makes is to drop trailing whitespace.
This makes contributions easier for folks whose editors are set up
to automatically remove such whitespace on save.
> Drop trailing whitespace

- src/vk_mem_alloc.h
This is a port of an optimization I did for rpcs3 here: https://github.com/RPCS3/rpcs3/commit/5a049d41fd06fb4f75cfb0d955cdbe8f0c5d921e
Basically, avoids scanning suballocations when there is no need to. When allocAlignment and bufferImageGranularity are the same, a lot of time can be saved when managing thousands of small allocations frequently.
1. When aligning resulting offset, the alignment is already done beforehand to the allocAlignment. The whole reason to check for conflicts is to align the result to the bufferImageGranularity as a worst case fallback, but this is clearly not needed when allocAlignment = bufferImageGranurality.
2. When checking for conflicts after allocation, there is no need to check suballocations if the 'page' is perfectly aligned start and end.
Combining this …
> mem_alloc: Optimize allocation conflict checking

- include/vk_mem_alloc.h
The bug has been fixed now: https://github.com/KhronosGroup/MoltenVK/issues/175
> Remove reference to MoltenVK issue 175 which is fixed now

- include/vk_mem_alloc.h
The copy constructor must be explicitly defined (here, defaulted) to be
available when the assignment operator is deleted.  While there is a
templated constructor from VmaStlAllocator<U>, the compiler doesn't
consider this to be a "copy" constructor for purposes of the warning.
> Fix clang -Wdeprecated-copy.

- include/vk_mem_alloc.h
See: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/184
> Disable aligned_alloc on macOS 11.0+ and revert behaviour.

- CMakeLists.txt
This change makes sure the right vulkan headers can be include using `#include<vulkan/vulkan.h>` and makes sure that the imported headers are those from FindPackage() rather than those found in system include paths. (Currently VMA does not build on macOS for example as the default header paths do not include vulkan headers, even when sdk is installed correctly.)
> Add include_directories to CMake to include the header files.

- .travis.yml
Linux build failed because the build directory already exists,. Now the build will be really done so it's possible there is some other cause of failure for a travis linux build.
> Do not fail travis build if the build directory already exists.

- include/vk_mem_alloc.h
Just a minor change to prevent unwanted diffs when vendoring this lib in other codebases (due to `.editorconfig` or IDE configuration).
---
BTW, this repo uses a mix of files with LF (Unix-like) line endings and CRLF (DOS-like). I would suggest standardizing on LF like most repos do (which can still be checked out as CRLF on Windows and converted to LF on push). If this is wanted, I can work on a PR to do that.
> Remove trailing whitespace

- include/vk_mem_alloc.h
`VK_ERROR_UNKNOWN` was added in the first Vulkan 1.2 SDK (https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.2.131). The define is to maintain the compatibility with the previous sdks.
> Compatibility fix with old sdks where VK_ERROR_UNKNOWN is not defined

- include/vk_mem_alloc.h
move variable dedicatedAllocInfo outside the if block in case of destruct of dedicatedAllocInfo
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L15498
> fix crash in VmaAllocator_T::AllocateDedicatedMemory

- include/vk_mem_alloc.h
The overloaded signature of `VmaCreateStringCopy` with a `size_t strLen` argument is only used together with `VmaStringBuilder` (in lines [15154](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/4f24cf28c8f48fb1c140f183d037211ef2fe39ca/include/vk_mem_alloc.h#L15154) and [16370](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/4f24cf28c8f48fb1c140f183d037211ef2fe39ca/include/vk_mem_alloc.h#L16370)). So, if we `#define VMA_STATS_STRING_ENABLED 0` it is still declared but no longer used.
This triggers an "[unreferenced local function has been removed](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4505?view=msvc-170)" warning on MSVC when compiling with `/W4`.
This PR wraps the overload declaration …
> Fix MSVC warning C4505 for VmaCreateStringCopy

- include/vk_mem_alloc.h
After commit https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/12d128d8f7f5dd1752eec5a644e6aa7eb21efd89, if we `#define VMA_STATS_STRING_ENABLED 0` and also add a custom definition for `VMA_DEBUG_LOG`, we then hit a compilation error:
```
vk_mem_alloc.h(6053,1): error C2065: 'VMA_SUBALLOCATION_TYPE_NAMES': undeclared identifier
vk_mem_alloc.h(6053,1): error C2039: 'GetBufferImageUsage': is not a member of 'VmaAllocation_T'
vk_mem_alloc.h(5613): message : see declaration of 'VmaAllocation_T'
vk_mem_alloc.h(6053,1): warning C4473: 'printf' : not enough arguments passed for format string
vk_mem_alloc.h(6053,1): message : placeholders and their parameters expect 5 variadic arguments, but 3 were provided
vk_mem_alloc.h(6053,1): message : the missing variadic argument 4 …
```
> Fix VMA_STATS_STRING_ENABLED 0 with VMA_DEBUG_LOG

- include/vk_mem_alloc.h
Hi, upon updating my local fork my compilation started hitting the following assert:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/4d65f7e113480be158f85e6f924b3d775e215a2b/include/vk_mem_alloc.h#L14582-L14587
This happens because in commit https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/5c710e86a0ce0664bbc2374c39b956b9928b2f29 the definition of `VMA_VULKAN_VERSION` was moved before the include of `<vulkan/vulkan.h>`. So, instead of `1002000` it is now being set to `1000000` (on the `#else` branch), since I'm not including vulkan.h myself in the `.cpp` file where I define `VMA_IMPLEMENTATION`.
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/4d65f7e113480be158f85e6f924b3d775e215a2b/include/vk_mem_alloc.h#L132-L142
I …
> Include vulkan.h before #define VMA_VULKAN_VERSION

- include/vk_mem_alloc.h
`push_back ` on an empty `VmaSmallVector` skipped the first element
> Fix VmaSmallVector::push_back

- include/vk_mem_alloc.h
These are the two actual bugs I have so far run into when trying the new defragmentation API. The first commit fixes a bug that makes the defragmenter unusable if not set to extensive because the loop never terminates (unless you count segfaults). The second is a bit more insidious: I _think_ this is the right place to put the lock, based on the rest of the code, but it is possible that this leads to recursive locking which is a-okay on Windows but not with Linux/Mac pthreads. As best as I can tell this should work, but you probably want to double check that as well.
> Fixed two issues with the new defragmenter

- include/vk_mem_alloc.h
After commit https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/3c6470cf45816999f906c2dec18ec15a57652000, the `VmaAlgorithmToStr` function is no longer used (which was previously called in `VmaBlockVector::PrintDetailedMap`).
Removing it fixes the following MSVC compier warning: `vk_mem_alloc.h(3381,20): warning C4505: 'VmaAlgorithmToStr': unreferenced function with internal linkage has been removed`.
> Remove unused VmaAlgorithmToStr function

- include/vk_mem_alloc.h
Returning `void* const` doesn't mean anything (and produces a warning with -Wignored-qualifiers). Based on usage, it looks like the returned pointer is expected to point at const data, so I've fixed the declaration to reflect that.
> Fix return type of GetAllocationNextPtr

- src/VmaUsage.h
The header provided by mingw-w64 on Linux is called windows.h.
> Fix windows.h not found when cross compiling on Linux

- include/vk_mem_alloc.h
Fixes #290. size_t is not uint32 or uint64 on iOS, so use explicit casts when calling WriteSize with a size_t
> Fix build for iOS

- include/vk_mem_alloc.h
This effectively reverts some of the changes from commit 4dfa169ffc65583cd35bdb7ec13057cde8897c66, pertaining to the `AtomicTransactionalIncrement` class. The problem with them is that they broke compilation when a custom atomic type is defined with `VMA_ATOMIC_UINT32`.
In `VmaAllocator_T::AllocateVulkanMemory()` a call to `AtomicTransactionalIncrement::Increment()` is given as argument a reference to the `m_DeviceMemoryCount`. But the latter will be of the user-defined `VMA_ATOMIC_UINT32` type, while the method expects to be passed a value of the `std::atomic` type.
Reverting those changes has fixed the compilation error with custom atomic types defined.
> Fix atomic type used in AtomicTransactionalIncrement

- include/vk_mem_alloc.h
Detected during inclusion of this library in Blender when compiling using GPU 11.2.0/Linux.
The compiler suggests to add the parentheses around the '&&', but makes more sense
to add them around the '||' as the message is to inform the developer about the issue.
> Fix compilation warning.

- include/vk_mem_alloc.h
I caught `VMA_ASSERT(m_VulkanFunctions.vkGetPhysicalDeviceMemoryProperties2KHR != VMA_NULL);` in `ValidateVulkanFunctions` when I was switching VMA to 1.1 for [0 A.D.](https://play0ad.com/) (we use manually provided Vulkan  functions via `VmaVulkanFunctions`).
> Fixes uninitialized vkGetPhysicalDeviceMemoryProperties2KHR

- include/vk_mem_alloc.h
Whereas __alignof is a non-standard compiler extension that seems to come from Microsoft and is supported (yet undocumented) by Clang and GCC, alignof is a standard language feature in C++11. Clang and GCC both document __alignof__ as a compiler extension, but this isn't supported by Microsoft.
This fixes builds on compilers that don't support __alignof.
> Change __alignof to alignof

- include/vk_mem_alloc.h
This PR adds an attribute `VMA_EXTENDS_VK_STRUCT` similar to `VMA_LEN_IF_NOT_NULL` that allows detecting programatically which Vulkan structure will be extended with a given `pNext` argument.
For example:
```c++
VMA_CALL_PRE VkResult VMA_CALL_POST vmaBindBufferMemory2(
VmaAllocator VMA_NOT_NULL allocator,
VmaAllocation VMA_NOT_NULL allocation,
VkDeviceSize allocationLocalOffset,
VkBuffer VMA_NOT_NULL_NON_DISPATCHABLE buffer,
const void* VMA_NULLABLE VMA_EXTENDS_VK_STRUCT(VkBindBufferMemoryInfoKHR) pNext);
```
with this attribute, generators can detect and enforce that `pNext` points to a structure that is allowed to be present in the `pNext` chain of `VkBindBufferMemoryInfoKHR`.
> Add attribute to mark pNext pointers with the Vulkan struct they extend

- CMakeLists.txt
- src/CMakeLists.txt
- src/cmake/install_target.cmake
Vulkan headers directory is always needed because `vulkan/vulkan.h` is included in `src/VmaUsage.h` and `include/vk_mem_alloc.h`.
And the fix for https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/303 was wrong. If `Vulkan::Headers` is already available when VulkanMemoryAllocator is added as a subdirectory, then `find_package(Vulkan)` in `VulkanMemoryAllocator/CMakeLists.txt` will not be executed.
Example code:
```
add_subdirectory(Vulkan-Headers)
set(VMA_STATIC_VULKAN_FUNCTIONS OFF)
set(VMA_DYNAMIC_VULKAN_FUNCTIONS ON)
add_subdirectory(VulkanMemoryAllocator) # VulkanMemoryAllocator will use the headers from the above directory
```
> cmake: always add vulkan headers dir

- src/cmake/Config.cmake.in
`find_package(VulkanMemoryAllocator)` (without `REQUIRED`) should not fail if `Vulkan` is not found.
> cmake: correctly use find_dependency

- CMakeLists.txt
See the following discussion for context:
https://discourse.cmake.org/t/what-should-the-destination-be-for-a-header-only-librarys-cmake-config-file/8473/2
NOTE: I've never seen this cause an issue before, but better safe than sorry. Also I think it reads a bit better.
I recently did this for VulkanHeaders so I'd like this fixed here as well.
> cmake: Use share instead of DATADIR for CMake config files

- src/CMakeLists.txt
- src/VmaUsage.h
No need to include via `../include`
By linking against `GPUOpen::VulkanMemoryAllocator` the proper include directory is added to the project.
> Fixup include of "vk_mem_alloc.h"

- CMakeLists.txt
The documentation is generated but not installed.
And if only the project name was still `VulkanMemoryAllocator` then
```
install(DIRECTORY docs/ DESTINATION "${CMAKE_INSTALL_DATADIR}/doc/VulkanMemoryAllocator" PATTERN ".nojekyll" EXCLUDE)
```
could have been simply:
```
install(DIRECTORY docs/ TYPE DOC PATTERN ".nojekyll" EXCLUDE)
```
By the way,
```
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
```
can be simplified to:
```
install(DIRECTORY include/ TYPE INCLUDE)
```
> cmake: install docs

- README.md
Thank you for Vulkan Memory Allocator library. Wicked Engine has been using this library for a long time with good success.
> added Wicked Engine to software list

- include/vk_mem_alloc.h
- Some compilers with C++20 dont have std::popcount
- Support to toggle C++20 features from user side using new VMA_CPP20 macro. If the macro is not defined, it will be set using default logic - #if __cplusplus >= 202002L || _MSVC_LANG >= 202002L
> Make C++20 features optional

- include/vk_mem_alloc.h
Remove this semicolon to fix ISO C warnings
> Remove semicolon outside function

- include/vk_mem_alloc.h
Getting rid of leaks is important.
VMA has some facilities that aid in tracking down leaks, but they don't seem to be mentioned in the docs.
Attempt to provide a section on them.
> Attempt to document leak detection aids

- README.md
- include/vk_mem_alloc.h
This PR fixes a set of typos in the docs. Here is a list of them:
- 'lincese' -> 'license'
- 'ofsets' -> 'offsets'
- 'instrinsics' -> 'intrinsics'
- 'becase' -> 'because'
- 'availeble' -> 'available'
- 'mesure' -> 'measure'
- 'parametrs' -> 'parameters'
> Fix documentation typos

- include/vk_mem_alloc.h
- ```#include <vulkan/vulkan.h>``` adds dependency on include directory being set externally
- Dont include vulkan.h if ```VULKAN_H_``` is already defined (if the Vulkan header is already included)
> Make Vulkan include optional

- src/VulkanSample.cpp
Closes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/421
Please verify if this solution is technically correct.
Tested on NVIDIA RTX 3090, NVIDIA GeForce 940M, Intel Arc A770, and AMD Ryzen 9 7950X.
Have a nice weekend
Johannes
> Fix swapchain semaphore handling

- CMakeLists.txt
Like in [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/blob/e3c37e6e184a232e10b01dff5a065ce48c047f88/CMakeLists.txt#L95-L96). It allows specifying version constraint: `find_package(VulkanMemoryAllocator 3.1.0 REQUIRED)`
> cmake: add package version file

- src/Tests.cpp
- src/VulkanSample.cpp
Closes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/423
This is not used in the tests yet though.
This now is the resource list in RenderDoc:
Note: We can't assign names to the physical devices which are present, but not chosen. This is why there are two resources with default names "Physical Device".
> Use SetDebugUtilsObjectName

- include/vk_mem_alloc.h
I believe that the error code checking in `vmaCreateImage` is wrong, possibly causing null pointer dereferencing issues, if allocation fails. The checks in this method test the result value against `>= 0`, which should always evaluate to `true`, as `VK_SUCCESS` is defined as `0` and all errors are integers greater than that. This function is the only function that tests results this way.
This PR replaces the checks by explicitly testing against `VK_SUCCESS`, which I believe is the intended behavior.
For context, I've encountered this issue, as clang-tidy complained about a possible null pointer deref here: 
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/05973d8aeb1a4d12f59aadfb86d20decadba82d1/include/vk_mem_alloc.h#L16161-L16188
... which from my understanding can …
> Fix ineffective error code checks.

- src/VmaUsage.h
Closes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/456
Does this fix it? @FuXiii
> Include vulkan_win32.h only for Windows

- src/SparseBindingTest.cpp
- src/Tests.cpp
* Fix a small typo in `Tests.cpp`
* Remove unrequired code in `SparseBindingImage::Init` related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/364
> Small maintenance

- .github/workflows/build.yml
Related to https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/467
We can already use [GitHub actions](https://github.com/features/actions) for continuous integration (CI) for the Windows build.
This workflow builds the code using MSVC compiler and clang for Windows, each in both debug and release configuration.
The results are uploaded as artifacts in a nightly build.
Let me know if you request changes to the workflow.
best regards
Johannes
> Add GitHub workflow for continuous integration for Windows

- .github/workflows/build.yml
One more thing about https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/pull/469:
I removed windows clang build in CI because it's not working for now.
Maybe I can find a way to use clang for Windows using some offical repositories.
> Remove unrequired Windows clang build in GitHub

- src/Tests.cpp
Closes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/433
What do you think? The new tests don't show any validation layer warnigns or errors on my system.
I still need to find a way to link the code in the doxygen documentation, but that's for another pr.
I still have some **questions**:
1) In `TestDataUploadingWithStagingBuffer`, I explicitely check if the memory did not end up in mappable memory with `TEST(!(memPropFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT));`. Does this make sense like this? Because if this is not true, it would be a bug in vma, right? (The same argument is for `TEST(memPropFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);` in `TestDataUploadingWithMappedMemory`).
2) Besides `vmaFlushAllocation`, should we maybe also mention in a comment that …
> Add new tests for advanced data uploading

- .github/workflows/linux.yaml
Reverts GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#478
Build failed!
> Revert "Enable all gcc and clang warnings for testing the CI"

- .github/workflows/linux.yaml
Closes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/480
Please check if this can run before merging. For some reason I can't run it in my forked repo.
The warnings should not break the CI. If you want any warnings to be removed let me know.
> Enable extra warnings for clang and gcc in CMake

- .github/workflows/static_code_analysis.yaml
* Use clang-tidy to perform static code analysis 
* Ignore warnings `-modernize-use-trailing-return-type`, `cppcoreguidelines-macro-usage`, `modernize-use-auto`
clang-tidy is very powerful, but it needs proper configuration because you sometimes disagree with some things it comes up with. Let me know if you have further warnings to add to the ignore list. Still, I find it interesting what it already can find.
> Add workflow for static code analysis using clang-tidy

- .github/workflows/static_code_analysis.yaml
See https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/484
Please check if this runs correctly
(Sometimes I can't run the CI in my fork, I don't know why but it seems to be an issue with GitHub).
> Add more warnings to ignore list of clang-tidy for static code analysis

- .github/workflows/linux.yaml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/windows.yaml
Closes #490 
On the second run, the step of downloading Vulkan SDK should be skipped in build (windows and linux) as well as in clang-tidy.
Here's an example of Windows MSVC debug build:
> Use a cache instead of downloading Vulkan SDK with every CI run

- src/Tests.cpp
`vmaFlushAllocation` is unnecessary here because [vmaCopyMemoryToAllocation](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ga11731ec58a3a43a22bb925e0780ef405) does that internally if it's required.
This small mistake made it somehow through when discussing pull request https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/pull/474.
I only found this in this test, the others seem to be correct.
> Small improvements of tests

- include/vk_mem_alloc.h
Based on https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/pull/500
> Fixed for some compiler warnings

- include/vk_mem_alloc.h
- src/Tests.cpp
I have added an import function for Win32 Handle and also added `vmaGetMemoryWin32Handle2` that can export handle with supplied handle type. Note that Allocator **must** be created with support for supplied handle type.
Closes #499
> Added Win32 Import function prototype
