src/vk_mem_alloc.h
Can you try the demo on Windows.
I tested compilation, it's ok.
But the sample only works on Windows and I have Linux.
So can you try the sample to be sure that runtime works.
Thanks
=> Fix vulkan calls

src/vk_mem_alloc.h
Reverts GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#28
=> Revert "Unbreak on BSDs"

src/vk_mem_alloc.hpp
Warning! The binding has **not** been tested!
=> Add a C++ binding

README.md
SInce vkQuake2 is now public, it might as well be added to the list!
=> Added vkQuake2 to list of software that uses VMA.

src/vk_mem_alloc.h
The issue here is that `VmaBlockVector::DefragmentationEnd()` relied on the mutex being previously locked to safely mutate its data, but with incremental defrag this isn't guaranteed to be the case anymore.
=> Fixed a race condition with incremental defragmentation. 

README.md
At the moment this is licensed as BSD and has my name on the copyright.
I think that given it's basically reproducing what's here in a different
format this isn't entirely appropriate. Do you have any guidance?
=> Mention Haskell bindings in readme

src/vk_mem_alloc.h
=> Return VkResult in vmaInvalidateAllocation and vmaFlushAllocation

src/vk_mem_alloc.h
Hey Adam!  I keep running into build errors when I turn on debugging because of this.  Cheers.
=> Refer to std string and stream with their fully qualified names.

include/vk_mem_alloc.h
I used Visual Studio Code's spell checker for that.
=> Minor typo fixes in code comments

README.md
The X-Plane Vulkan renderer is build around VMA as its memory allocation backend and has been shipping since late 2019. We make heavy use of the defragmentation feature and have very aggressive streaming of world data as well as texture paging. Planes are quite fast and earth is quite large, so we constantly move memory around and dynamically adjust things as the memory budget grows or shrinks and the user moves around. It's absolutely rock solid on top of VMA :)
=> Added X-Plane to the list of software using VMA

README.md
=> Add PPSSPP to the "Software using this library" section of README.md

include/vk_mem_alloc.h
Hi, See topic - The same problem as 8da08d160a58dcd2111332dc9eb8c1c8f08aa83e
=> Fix build - removed usage of DWORD type

include/vk_mem_alloc.h
=> Fix build - 64 bit functions do not exist

include/vk_mem_alloc.h
For fixing build errors on Clang, like here: https://github.com/RandomShaper/godot/runs/5317274779
=> Add missing nullability qualifier

include/vk_mem_alloc.h, src/Common.cpp, src/SparseBindingTest.cpp, src/Tests.cpp, src/VulkanSample.cpp
Will conflict with #272 for the VMA header, I'll rebase as needed.
=> Strip trailing whitespace in code files

include/vk_mem_alloc.h
=> allow building against vulkan 1.2.131 headers

CMakeLists.txt, src/CMakeLists.txt
Broken up into 3 atomic commits
=> Minor CMake cleanup

include/vk_mem_alloc.h
Discoverd with upcoming GCC 13.
=> IWYU: add cstdio for snprintf in vk_mem_alloc.h

.gitignore
Quality of life for vscode users
=> git: ignore .vscode directory

README.md
https://projects.blender.org/blender/blender/src/branch/main/extern/vulkan_memory_allocator
=> README.md: add Blender ref

include/vk_mem_alloc.h
=> Use format specifier PRIu64 only with uint64_t types

include/vk_mem_alloc.h
Closing https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/426
=> Improve sample code for advanced data uploading in docs

include/vk_mem_alloc.h
=> Fix for vkGetMemoryWin32HandleKHR

include/vk_mem_alloc.h
`vmaCopyMemoryToAllocation` is used in the tests, so it should be used in the docs as well.
=> Small improvement of 'advanced data uploading' exampe in docs
